### ISSUE TITLE
а що за "new strict"?)

### ISSUE THREAD

**Issue by Nazar32** [xom-dev/trudyaga#1]
https://github.com/xom-dev/trudyaga/blob/6c67047290c7be54e78ea3d7b225e6a10f189bf3/func.js#L1

**Comment by Nazar32** [comment]
https://developer.mozilla.org/uk/docs/Web/JavaScript/Reference/Strict_mode

**Comment by xom-dev** [comment]
Там в цьому современному учєбніку писало шо треба цю хуйню

**Comment by xom-dev** [comment]
Поняв має бути 'use' це я далбайоб
